#!/usr/bin/env bash

action=$1
shift

[ "$1" = "usage" ] && {
  echo "  Remind:"
  echo "    $TODO_SH remind ITEM# DATE TIME"
  echo "      create a reminder out of the todo item with an alert time"
  echo ""
  exit
}

case "$1" in
[0-9]*)
	getTodo "$1"
	alert_date=$(date -j -f "%Y-%m-%d" "+%m/%d/%Y" "$2")
	alert_time=$(date -j -f "%H:%M" "+%I:%M%p" "$3") 

$TODO_SH append "$1" "#reminded"

osascript - "$todo" "$alert_date" "$alert_time" <<END
on run argv
    set stringedAll to date (item 2 of argv & " " & item 3 of argv)
    tell application "Reminders"
	tell list "Reminders" of default account
		make new reminder with properties {name:item 1 of argv, remind me date:stringedAll}
	end tell
    end tell
end run
END
;;
*)
	echo "Usage: $TODO_SH remind ITEM# DATE TIME"
esac
