#!/usr/bin/env bash

action=$1
shift

[ "$1" = "usage" ] && {
  echo "  Remind:"
  echo "    $TODO_SH remind ITEM# DATE TIME"
  echo "      create a reminder out of the todo item with an alert time"
  echo ""
  exit
}

case "$1" in
[0-9]*)
	getTodo "$1"
	alert_date=$(date -j -f "%Y-%m-%d" "+%m/%d/%Y" "$2")
	alert_time=$(date -j -f "%H:%M" "+%I:%M%p" "$3") 

	reminderID=$(osascript -e "tell application \"Reminders\" to tell list \"$REMINDERS_LIST\" of default account to make new reminder with properties {name:\"$todo\", remind me date:date (\"$alert_date $alert_time\")}" | sed "s_\(reminder id x-apple-reminder://\)\(.*\)_\2_")
	$TODO_SH append "$1" "reminder:$reminderID"
;;
*)
	echo "Usage: $TODO_SH remind ITEM# DATE TIME"
esac
